theme: jekyll-theme-cayman
title: RHDH Setup Guide
description: Comprehensive guide for deploying MTA plugins with Red Hat Developer Hub
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
source: docs
destination: _site/docs
baseurl: /rhdh-documentation
